# Generated by Django 5.2.5 on 2025-08-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
