# Generated by Django 5.2.5 on 2025-08-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_sermon_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='DonationInfo',
        ),
    ]
