# Generated by Django 5.2.5 on 2025-08-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_delete_contact_delete_donationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeyear',
            name='verset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
